# Generated by Django 4.0.3 on 2022-03-28 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='curbid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watchedby',
            field=models.ManyToManyField(null=True, related_name='mywatchings', to=settings.AUTH_USER_MODEL),
        ),
    ]
