# Generated by Django 4.0.3 on 2022-03-28 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_curbid_alter_listing_watchedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='curprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='startbid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watchedby',
            field=models.ManyToManyField(related_name='mywatchings', to=settings.AUTH_USER_MODEL),
        ),
    ]
