# Generated by Django 4.0.3 on 2022-03-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_comment_listing_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datettime',
            new_name='datetime',
        ),
    ]
