# Generated by Django 4.0.3 on 2022-03-31 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_datettime_comment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closedatettime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='curbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watchedby',
            field=models.ManyToManyField(blank=True, related_name='mywatchings', to=settings.AUTH_USER_MODEL),
        ),
    ]
